name: oro_high_scanner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.5
  flutter_dotenv: ^5.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8  # Fixed the spelling
  intl: ^0.18.1
  equatable: ^2.0.5
  csv: ^6.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/orositebanner.png
    - asset/orosite.jpg
    - .env